### ISSUE TITLE
scroll: live reload doesn't preserve the scroll position

### ISSUE THREAD

**Issue by abuturabofficial** [McShelby/hugo-theme-relearn#1014]
When building locally, during a live reload, the page we working on goes to the start. Hugo provides an option:

```
hugo server --navigateToChanged
```

But that also doesn't work with relearn.

Other themes like `hugo stack theme` remains at the editing position during live reload, when using

```hugo
hugo server
```

But `relearn` always goes to the start of the page when live reloading no matter what flag is used.

**Comment by abuturabofficial** [comment]
Strangely 

```
hugo server --navigateToChanged
```

Now does remain to the position where it left before (actual, it should move to the changed portion)....

Earlier test even this behavior (which is somewhat acceptable) wasn't happening, didn't change anything and now this....

**Comment by McShelby** [comment]
Thanks for reporting. I can confirm that there is something unexpected going on. I need to examine this further.

**Comment by abuturabofficial** [comment]
@McShelby Oh, thanks for acknowledging the issue.

Out of nowhere, today, it behaves normally. I was thinking it's just me, who has something weird going on.

(I'm on Fedora KDE spin, using hugo version `hugo v0.142.0-1f746a872442e66b6afd47c8c04ac42dc92cdb6f+extended`, manually downloaded from their GitHub, and added to the path.)

**Comment by McShelby** [comment]
@abuturabofficial I had a hard time to recreate this consistently. Nevertheless I've fixed a bug. Could you recheck?

**Comment by abuturabofficial** [comment]
> [@abuturabofficial](https://github.com/abuturabofficial) I had a hard time to recreate this consistently. Nevertheless I've fixed a bug. Could you recheck?

I will test and  report back. (Even I couldn't reproduce the bug consistently earlier.)

**Comment by abuturabofficial** [comment]
@McShelby It seems, issues isn't fixed yet.
https://github.com/user-attachments/assets/e352362a-06fc-4b84-b3e7-8e299aeacd05

(I have downloaded the theme as a ZIP file latest commits.)

**Comment by McShelby** [comment]
To assert you are running the correct version:

- please press CTRL+U in your browser. At the beginning of the <head> (if not otherwise configured in your Hugo Project) there should be written: `<meta name="generator" content="Relearn 7.3.2+85824e217f13a7e86def63c09505d6e04cdbd358">`
- open the deveoloper tools of your browser and open the file theme.js. Search for `debounce`. If you can find it, you are running the latest version.

Just to make sure, repeat your test afterwards and report your result.

**Comment by abuturabofficial** [comment]
My bad, I should have tested with `--navigateToChanged` flag. I use stack theme too, for which that's not necessary.

Anyhow, I will check again tomorrow with the proper flag and report.

**Comment by abuturabofficial** [comment]
I have manually checked the version number in the partials dir as well as the changes I'm the theme.js file (just to make sure..) in my local copy. But still i will test it again tomorrow with proper flags.

**Comment by McShelby** [comment]
Okay. Just for information: The version number changes with each commit. So if you pull now, you'll most likely will have a different version hash.

But the `debounce` test should be sufficient to validate the correct theme version.

**Comment by abuturabofficial** [comment]
I guess you're right about:

> Nevertheless, the theme should scroll to the last position you were before the reload happend. This did not work before my patch.

I was expecting it move to very line, the change is happening, which isn't the case now.

Maybe it's the limitation of hugo...... Anyway I have tested and can confirm, with `--navigatetoChanged` flag, it will remain at the last modified part.
